### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by rikakohira** [rikakohira/protospace-38304#1]
### ProtoSpaceのURL
https://protospace-38304.herokuapp.com/

よろしくお願いいたします。

**Comment by snkw-works** [comment]
@rikakohira さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できるよう修正しましょう**
ログイン状態の投稿者であっても、編集ページに遷移できない状態です。

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるよう修正しましょう**
コメントを空欄のまま送信すると、エラー画面に遷移してしまいます。
<img width="675" alt="スクリーンショット 2022-08-02 14 39 00" src="https://user-images.githubusercontent.com/54050089/182299970-8ccb7387-bb87-445b-9d38-dafa067e0542.png">

※編集機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by rikakohira** [comment]
コードレビューありがとうございます。
２ヶ所修正いたしました。
- editアクションの修正
- コメント機能の修正

よろしくお願いいたします。

**Comment by motomuun** [comment]
@rikakohira さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、先程依頼した箇所の修正が出来ておりませんでした。
修正が完了している場合は、正しくデプロイが出来ているかの確認の上、再度提出をお願いします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@rikakohira さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ編集機能**

- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
トップページに遷移します。詳細ページへ遷移するように修正をお願いします。

- [x] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
編集ページに留まった場合、入力済みの項目が消えてしまいます。こちらが消えないように修正をお願いします。



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by rikakohira** [comment]
コードレビューありがとうございます。
修正しましたので、ご確認お願いいたします。

**Comment by snkw-works** [comment]
@rikakohira さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
